trainer: forces

dataset:
  - src: ff-all90-train/sample-train/
    normalize_labels: True
    target_mean: 3.836506027740973
    target_std: 2.5204004699584366
    grad_target_mean: 0.0
    grad_target_std: 0.7249166287107405
  - src: ff-all90-train/sample-valid/ 

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True

model:
  name: dimenetplusplus
  hidden_channels: 512
  out_emb_channels: 384
  num_blocks: 3
  cutoff: 6.0
  num_radial: 6
  num_spherical: 7
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: True

# *** Important note ***
#   The total number of gpus used for this run was 64.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 1
  eval_batch_size: 1
  eval_every: 100000
  num_workers: 1
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 523179
    - 784769
    - 1046359
  warmup_steps: 523179
  warmup_factor: 0.2
  max_epochs: 50
  energy_coefficient: 0
  force_coefficient: 100
